# Arquivo de Configuração - Usuario decide qual serviço devem ser filtrados, e inserir os tipos de logs que devem ser filtrados
# Melhora consideravel em customização de filtragem inicial para cada caso

Flask: 
    admin_account_failed: 'nerdy-web flask\[\d+\]: Failed password for admin from .*'
    nerdy_account_failed: 'nerdy-web flask\[\d+\]: Failed password for nerdy from .*'
    admin_account_accepted: 'nerdy-web flask\[\d+\]: Accepted password for admin from .*'
    nerdy_account_accepted: 'nerdy-web flask\[\d+\]: Accepted password for nerdy from .*'
    recon_by_trying_access_inexistent_page: 'nerdy-web flask\[\d+\]: 404 Not Found: /.*'
    normal_access_failed: 'nerdy-web flask\[\d+\]: Failed password for .*'
    normal_access_accepted: 'nerdy-web flask\[\d+\]: Accepted password for .*'

Nginx: 
    Failure: 'nerdy-web flask\[\d+\]: Failed password for .'
    Accepted: 'nerdy-web flask\[\d+\]: Accepted password for'